services:
  # 1. Spring Boot Java STS Backend API
  - type: web
    name: tourtec-backend
    runtime: docker
    dockerfilePath: Dockerfile.backend
    dockerContext: .
    plan: free
    envVars:
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        fromDatabase:
          name: tourtec-db
          property: connectionString

  # 2. Frontend React / Vite Web App
  - type: web
    name: tourtec-frontend
    runtime: static
    buildCommand: npm --prefix frontend install && npm --prefix frontend run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: tourtec-backend
          property: host
      - key: VITE_GOOGLE_CLIENT_ID
        value: 849997510284-lb00lknh9vfbhrhj2pfhmkiqr9qcdgei.apps.googleusercontent.com

databases:
  # 3. PostgreSQL Managed Database
  - name: tourtec-db
    databaseName: tourtec_db
    user: tourtec_user
    plan: free
